### PR TITLE
Svelte refactor

### PR DESCRIPTION
**Pull request by perryd01**

### CODE REVIEW

**Comment by gergoradeczki** [comment]
Thank you for your contribution! It's nice to see that you still care about schdesign even after becoming a senior member.

While you were (are?) away from schdesign, there was a decision made regarding the Logotar project (2-3 months ago) and new works will begin in January. Because of this decision, please be prepared that your work in this PR will (very likely) be in vain.

If you'd like to contribute to our projects in the future, please reach out to the new presidency of Simonyi or the new leader of schdesign regarding the opportunities.

**Comment by perryd01** [comment]
> Thank you for your contribution! It's nice to see that you still care about schdesign even after becoming a senior member.
> 
> While you were (are?) away from schdesign, there was a decision made regarding the Logotar project (2-3 months ago) and new works will begin in January. Because of this decision, please be prepared that your work in this PR will (very likely) be in vain.
> 
> If you'd like to contribute to our projects in the future, please reach out to the new presidency of Simonyi or the new leader of schdesign regarding the opportunities.

well, its nice to see that you are finally willing to fix your solution after 3 years of waiting.
Expropriation of projects are also cool! Keep up the good work! :)

**Comment by gergoradeczki** [comment]
@perryd01 I know we never had the best relation in schdesign, but that doesn't justify your always passive aggressive behavior and unwillingness to cooperate on a basic level. This has lead to many conflicts and I personally never saw any steps in the right direction from your part.

> well, its nice to see that you are finally willing to fix your solution after 3 years of waiting.

Let me tell you the story of the Logotar project. It started out as a simple React application with the logos being served statically from the repository. My "solution" to this was implementing an easy to use Google Drive workaround to the updating of logos problem. As you can see, this solution was far from perfect, because adding a new logo (or just adding anything new to the website) is not as straight forward as it should have been. If by "my solution" you are referring to the "Google Drive integration" then you are right, but if you are referring to the static storing of files, then you are wrong.

> Expropriation of projects are also cool! Keep up the good work! :)

You are completely wrong here. We do not gate-keep anyone from contributing to our projects. I simply asked you to get in touch with us through our official channels (which you must be familiar with because of your years long working in schdesign) in order to figure out how you can help us in making our products better and to avoid unnecessary works. Joining a completely unrelated call and bringing up the Logotar project is not the right way.

As far as we are aware, you left schdesign and became a senior member simultaneously. As a senior member, we do not expect any contribution from you (this was as a requirement for keeping your membership in the past). There is a big difference in being a **member** and being a **senior member** (you should be familiar with these terms).

I asked you to get in touch with us in an official way because, generally speaking, a senior member might not be up-to-date with the life of (in your case) schdesign and through this way we can be sure to avoid any unnecessary misunderstandings.

My original comment was written in good faith and I just wanted you not to waste your energy on something unrelated. Moving to Svelte is not on our roadmap for this project as it will make future development complicated because many of us are unfamiliar with Svelte.

**Comment by perryd01** [comment]
> My original comment was written in good faith and I just wanted you not to waste your energy on something unrelated. Moving to Svelte is not on our roadmap for this project as it will make future development complicated because many of us are unfamiliar with Svelte.

This is your only reasonable argument before saying `your work in this PR will (very likely) be in vain` and removing me from the schdesign team.

> We do not gate-keep anyone from contributing to our projects

Non-gatekeeping would look at the PR first, draw conclusions about the solution, and give a proper comment on that.

> As far as we are aware, you left schdesign and became a senior member simultaneously. As a senior member, we do not expect any contribution from you

I don't see any points here.

>  but that doesn't justify your always passive aggressive behavior

I would suggest you reread your message if you think that mine was the aggressive one.

Also please stop gaslighting and being a smart alec.

**Pull request closed without merging**
